Repository AY2223S1-CS2103T-W13-4/tp, pull requests merged in 2022-10, with the labels that each got.

#34 Add `delete_member` command
  src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMemberCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteMemberCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SetTeamCommandParser.java
  src/main/java/seedu/address/model/team/Team.java
  src/test/java/seedu/address/logic/commands/DeleteMemberCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteMemberCommandParserTest.java
Labels: priority.High

#33 Add `list_members` command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListMembersCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/TeamPredicate.java
  src/test/java/seedu/address/logic/commands/ListMembersCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#46 Support deleting of tasks
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/model/team/Team.java
Labels: type.Story, priority.High

#76 Add, Edit and Delete Links
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddLinkCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
  src/main/java/seedu/address/logic/commands/EditLinkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddLinkCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteLinkCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLinkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/team/Link.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueLinkList.java
  src/main/java/seedu/address/model/team/Url.java
  src/main/java/seedu/address/model/team/exceptions/DuplicateLinkException.java
  src/main/java/seedu/address/model/team/exceptions/LinkNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLink.java
  src/main/java/seedu/address/storage/JsonAdaptedTeam.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/EditLinkCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/team/LinkTest.java
  src/test/java/seedu/address/model/team/UrlTest.java
  src/test/java/seedu/address/storage/JsonAdaptedLinkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTeamTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditLinkDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalLinks.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#83 Update DG to include Add Task Functionality
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskActivityDiagram.puml
  docs/images/AddTaskActivityDiagram.png
Labels: type.Enhancement, priority.High

#89 Update DG with add_team and set_team features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTeamActivityDiagram.puml
  docs/diagrams/SetTeamActivityDiagram.puml
  docs/images/AddTeamActivityDiagram.png
  docs/images/SetTeamActivityDiagram.png
Labels: type.Enhancement, priority.High

#90 Add Randomly Assign Task description to DG
  docs/DeveloperGuide.md
  docs/diagrams/RandomlyAssignTaskActivityDiagram.puml
  docs/diagrams/RandomlyAssignTaskState0.puml
  docs/diagrams/RandomlyAssignTaskState1.puml
  docs/diagrams/RandomlyAssignTaskState2.puml
  docs/images/RandomlyAssignTaskActivityDiagram.png
  docs/images/RandomlyAssignTaskState0.png
  docs/images/RandomlyAssignTaskState1.png
  docs/images/RandomlyAssignTaskState2.png
Labels: type.Enhancement, priority.High

#73 Mark tasks as done and view list of completed or remaining tasks
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListTasksCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RandomlyAssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListTasksCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/team/Task.java
  src/main/java/seedu/address/model/team/TaskList.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/model/team/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, priority.High

#111 Delete member cascade
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/team/Task.java
  src/main/java/seedu/address/model/team/TaskList.java
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/UniqueTeamList.java
Labels: priority.High

#110 UI Changes
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: type.Enhancement, priority.High
